name: ci

on:
  pull_request:
  push:
    branches:
    - main
  workflow_call:
    inputs:
      release:
        description: Whether this is running as part of a release workflow.
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up toolchain
      run: rustup show
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Test
      run: cargo test --all-features --workspace
    - name: Lint
      run: cargo clippy --all-features --all-targets --no-deps --workspace
    - name: Build documentation
      run: cargo doc --all-features --no-deps --workspace

  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up toolchain
      run: |
        rustup install nightly
        rustup show
    - name: Enforce workspace dependencies
      run: |
        for crate in $(find sdk/ -maxdepth 2 -type f -name Cargo.toml); do
          eng/scripts/verify-dependencies.rs $crate
        done

  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up toolchain
      run: rustup show
    - name: Build documentation
      run: cargo doc --all-features --no-deps --workspace --target-dir '${{ runner.temp }}/docs'
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: ${{ runner.temp }}/docs

  check:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs:
    - test
    - verify
    - docs
    steps:
    - name: Fail
      if: ${{ contains(needs.*.result, 'fail') }}
      run: exit 1
